"""#732 probe: run test_marks_polar's tests one at a time, naming each on
stderr before it runs.

The module's own runner holds its output until the end, so a crash
takes every PASS line with it and the log never says which test died.
stderr is unbuffered, so the last START line here is the test that was
running when the process went down.

Generated by scripts/gen_polar_probe.py; delete with #732.
"""

from std.sys import stderr

from test_marks_polar import (
    test_render_arc_mark_matches_hand_derived_wedge_colors,
    test_render_arc_raises_on_negative_value,
    test_render_arc_raises_on_all_zero_values,
    test_render_arc_raises_on_mismatched_category_length,
    test_render_svg_arc_mark_matches_confirmed_wedge_paths,
    test_render_donut_leaves_the_center_unfilled_and_fills_the_ring,
    test_render_donut_svg_matches_confirmed_ring_sector_paths,
    test_render_donut_raises_on_out_of_range_inner_radius_fraction,
    test_render_nightingale_matches_hand_derived_wedge_colors,
    test_render_nightingale_area_mode_scales_radius_by_sqrt,
    test_render_nightingale_svg_matches_confirmed_wedge_paths,
    test_render_nightingale_raises_on_negative_value,
    test_render_nightingale_raises_on_all_zero_values,
    test_render_nightingale_raises_on_mismatched_category_length,
    test_render_nightingale_raises_on_no_data,
    test_render_polar_matches_hand_derived_line_and_markers,
    test_render_polar_draws_a_grid_even_with_no_data_on_it,
    test_render_polar_raises_on_mismatched_length,
    test_render_polar_raises_on_negative_radius,
    test_render_polar_raises_on_no_data,
    test_render_polar_several_series_matches_hand_derived_line_and_markers,
    test_render_polar_several_series_raises_on_mismatched_names_and_values_length,
    test_render_polar_several_series_raises_when_a_series_length_does_not_match_angle,
    test_render_polar_several_series_raises_on_negative_radius,
    test_render_polar_several_series_raises_on_empty_angle,
    test_render_polar_bar_matches_hand_derived_bar_colors,
    test_render_polar_bar_leaves_a_gap_between_bars,
    test_render_polar_bar_raises_on_negative_value,
    test_render_polar_bar_raises_on_all_zero_values,
    test_render_polar_bar_raises_on_mismatched_category_length,
    test_render_polar_bar_raises_on_no_data,
    test_render_radialbar_ring_colors_and_track,
    test_render_radialbar_leaves_a_radial_gap_between_rings,
    test_render_radialbar_raises_on_negative_value,
    test_render_radialbar_raises_on_all_zero_values,
    test_render_radialbar_raises_on_mismatched_category_length,
    test_render_radialbar_raises_on_no_data,
    test_render_radialbar_svg_matches_confirmed_ring_paths,
    test_render_radar_matches_hand_derived_polygon_fill,
    test_render_radar_overlapping_series_composite_instead_of_occluding,
    test_render_radar_raises_on_mismatched_indicator_length,
    test_render_radar_raises_on_mismatched_series_length,
    test_render_radar_raises_on_wrong_length_series_values,
    test_render_radar_raises_on_no_indicators,
    test_render_gauge_matches_hand_derived_needle_and_pivot,
    test_render_gauge_matches_hand_derived_band_colors,
    test_render_gauge_leaves_a_gap_at_the_bottom,
    test_render_gauge_clamps_values_beyond_the_range,
    test_render_gauge_raises_when_min_value_is_not_less_than_max_value,
    test_render_gauge_custom_breakpoints_matches_hand_derived_band_colors,
    test_render_gauge_custom_breakpoints_default_empty_matches_original,
    test_render_gauge_raises_on_mismatched_breakpoints_and_band_colors_length,
    test_render_gauge_raises_on_non_ascending_breakpoints,
    test_render_gauge_raises_on_out_of_range_breakpoint,
    test_render_parallel_matches_hand_derived_polylines,
    test_render_parallel_raises_on_mismatched_row_length,
    test_render_parallel_raises_on_wrong_length_row,
    test_render_parallel_raises_on_no_dims,
    test_render_single_axis_matches_hand_derived_points,
    test_render_single_axis_svg_matches_confirmed_circles,
    test_render_single_axis_color_encoding_reuses_point_channels,
    test_render_single_axis_raises_on_mismatched_channel_length,
    test_render_single_axis_raises_on_no_data,
    test_single_axis_tooltips_report_the_value_alone,
    test_a_wedge_is_titled_by_its_category_and_value,
    test_a_gauge_is_titled_by_its_one_value,
    test_a_gauge_s_tooltip_group_holds_only_the_needle,
    test_a_radar_ring_is_titled_by_its_series,
    test_radial_tooltips_follow_the_theme_flag,
    test_the_radial_value_marks_draw_their_values_on_request,
    test_a_wedge_label_sits_outside_its_wedge,
)


def main() raises:
    print("START 0 test_render_arc_mark_matches_hand_derived_wedge_colors", file=stderr)
    test_render_arc_mark_matches_hand_derived_wedge_colors()
    print("DONE  0 test_render_arc_mark_matches_hand_derived_wedge_colors", file=stderr)
    print("START 1 test_render_arc_raises_on_negative_value", file=stderr)
    test_render_arc_raises_on_negative_value()
    print("DONE  1 test_render_arc_raises_on_negative_value", file=stderr)
    print("START 2 test_render_arc_raises_on_all_zero_values", file=stderr)
    test_render_arc_raises_on_all_zero_values()
    print("DONE  2 test_render_arc_raises_on_all_zero_values", file=stderr)
    print("START 3 test_render_arc_raises_on_mismatched_category_length", file=stderr)
    test_render_arc_raises_on_mismatched_category_length()
    print("DONE  3 test_render_arc_raises_on_mismatched_category_length", file=stderr)
    print("START 4 test_render_svg_arc_mark_matches_confirmed_wedge_paths", file=stderr)
    test_render_svg_arc_mark_matches_confirmed_wedge_paths()
    print("DONE  4 test_render_svg_arc_mark_matches_confirmed_wedge_paths", file=stderr)
    print("START 5 test_render_donut_leaves_the_center_unfilled_and_fills_the_ring", file=stderr)
    test_render_donut_leaves_the_center_unfilled_and_fills_the_ring()
    print("DONE  5 test_render_donut_leaves_the_center_unfilled_and_fills_the_ring", file=stderr)
    print("START 6 test_render_donut_svg_matches_confirmed_ring_sector_paths", file=stderr)
    test_render_donut_svg_matches_confirmed_ring_sector_paths()
    print("DONE  6 test_render_donut_svg_matches_confirmed_ring_sector_paths", file=stderr)
    print("START 7 test_render_donut_raises_on_out_of_range_inner_radius_fraction", file=stderr)
    test_render_donut_raises_on_out_of_range_inner_radius_fraction()
    print("DONE  7 test_render_donut_raises_on_out_of_range_inner_radius_fraction", file=stderr)
    print("START 8 test_render_nightingale_matches_hand_derived_wedge_colors", file=stderr)
    test_render_nightingale_matches_hand_derived_wedge_colors()
    print("DONE  8 test_render_nightingale_matches_hand_derived_wedge_colors", file=stderr)
    print("START 9 test_render_nightingale_area_mode_scales_radius_by_sqrt", file=stderr)
    test_render_nightingale_area_mode_scales_radius_by_sqrt()
    print("DONE  9 test_render_nightingale_area_mode_scales_radius_by_sqrt", file=stderr)
    print("START 10 test_render_nightingale_svg_matches_confirmed_wedge_paths", file=stderr)
    test_render_nightingale_svg_matches_confirmed_wedge_paths()
    print("DONE  10 test_render_nightingale_svg_matches_confirmed_wedge_paths", file=stderr)
    print("START 11 test_render_nightingale_raises_on_negative_value", file=stderr)
    test_render_nightingale_raises_on_negative_value()
    print("DONE  11 test_render_nightingale_raises_on_negative_value", file=stderr)
    print("START 12 test_render_nightingale_raises_on_all_zero_values", file=stderr)
    test_render_nightingale_raises_on_all_zero_values()
    print("DONE  12 test_render_nightingale_raises_on_all_zero_values", file=stderr)
    print("START 13 test_render_nightingale_raises_on_mismatched_category_length", file=stderr)
    test_render_nightingale_raises_on_mismatched_category_length()
    print("DONE  13 test_render_nightingale_raises_on_mismatched_category_length", file=stderr)
    print("START 14 test_render_nightingale_raises_on_no_data", file=stderr)
    test_render_nightingale_raises_on_no_data()
    print("DONE  14 test_render_nightingale_raises_on_no_data", file=stderr)
    print("START 15 test_render_polar_matches_hand_derived_line_and_markers", file=stderr)
    test_render_polar_matches_hand_derived_line_and_markers()
    print("DONE  15 test_render_polar_matches_hand_derived_line_and_markers", file=stderr)
    print("START 16 test_render_polar_draws_a_grid_even_with_no_data_on_it", file=stderr)
    test_render_polar_draws_a_grid_even_with_no_data_on_it()
    print("DONE  16 test_render_polar_draws_a_grid_even_with_no_data_on_it", file=stderr)
    print("START 17 test_render_polar_raises_on_mismatched_length", file=stderr)
    test_render_polar_raises_on_mismatched_length()
    print("DONE  17 test_render_polar_raises_on_mismatched_length", file=stderr)
    print("START 18 test_render_polar_raises_on_negative_radius", file=stderr)
    test_render_polar_raises_on_negative_radius()
    print("DONE  18 test_render_polar_raises_on_negative_radius", file=stderr)
    print("START 19 test_render_polar_raises_on_no_data", file=stderr)
    test_render_polar_raises_on_no_data()
    print("DONE  19 test_render_polar_raises_on_no_data", file=stderr)
    print("START 20 test_render_polar_several_series_matches_hand_derived_line_and_markers", file=stderr)
    test_render_polar_several_series_matches_hand_derived_line_and_markers()
    print("DONE  20 test_render_polar_several_series_matches_hand_derived_line_and_markers", file=stderr)
    print("START 21 test_render_polar_several_series_raises_on_mismatched_names_and_values_length", file=stderr)
    test_render_polar_several_series_raises_on_mismatched_names_and_values_length()
    print("DONE  21 test_render_polar_several_series_raises_on_mismatched_names_and_values_length", file=stderr)
    print("START 22 test_render_polar_several_series_raises_when_a_series_length_does_not_match_angle", file=stderr)
    test_render_polar_several_series_raises_when_a_series_length_does_not_match_angle()
    print("DONE  22 test_render_polar_several_series_raises_when_a_series_length_does_not_match_angle", file=stderr)
    print("START 23 test_render_polar_several_series_raises_on_negative_radius", file=stderr)
    test_render_polar_several_series_raises_on_negative_radius()
    print("DONE  23 test_render_polar_several_series_raises_on_negative_radius", file=stderr)
    print("START 24 test_render_polar_several_series_raises_on_empty_angle", file=stderr)
    test_render_polar_several_series_raises_on_empty_angle()
    print("DONE  24 test_render_polar_several_series_raises_on_empty_angle", file=stderr)
    print("START 25 test_render_polar_bar_matches_hand_derived_bar_colors", file=stderr)
    test_render_polar_bar_matches_hand_derived_bar_colors()
    print("DONE  25 test_render_polar_bar_matches_hand_derived_bar_colors", file=stderr)
    print("START 26 test_render_polar_bar_leaves_a_gap_between_bars", file=stderr)
    test_render_polar_bar_leaves_a_gap_between_bars()
    print("DONE  26 test_render_polar_bar_leaves_a_gap_between_bars", file=stderr)
    print("START 27 test_render_polar_bar_raises_on_negative_value", file=stderr)
    test_render_polar_bar_raises_on_negative_value()
    print("DONE  27 test_render_polar_bar_raises_on_negative_value", file=stderr)
    print("START 28 test_render_polar_bar_raises_on_all_zero_values", file=stderr)
    test_render_polar_bar_raises_on_all_zero_values()
    print("DONE  28 test_render_polar_bar_raises_on_all_zero_values", file=stderr)
    print("START 29 test_render_polar_bar_raises_on_mismatched_category_length", file=stderr)
    test_render_polar_bar_raises_on_mismatched_category_length()
    print("DONE  29 test_render_polar_bar_raises_on_mismatched_category_length", file=stderr)
    print("START 30 test_render_polar_bar_raises_on_no_data", file=stderr)
    test_render_polar_bar_raises_on_no_data()
    print("DONE  30 test_render_polar_bar_raises_on_no_data", file=stderr)
    print("START 31 test_render_radialbar_ring_colors_and_track", file=stderr)
    test_render_radialbar_ring_colors_and_track()
    print("DONE  31 test_render_radialbar_ring_colors_and_track", file=stderr)
    print("START 32 test_render_radialbar_leaves_a_radial_gap_between_rings", file=stderr)
    test_render_radialbar_leaves_a_radial_gap_between_rings()
    print("DONE  32 test_render_radialbar_leaves_a_radial_gap_between_rings", file=stderr)
    print("START 33 test_render_radialbar_raises_on_negative_value", file=stderr)
    test_render_radialbar_raises_on_negative_value()
    print("DONE  33 test_render_radialbar_raises_on_negative_value", file=stderr)
    print("START 34 test_render_radialbar_raises_on_all_zero_values", file=stderr)
    test_render_radialbar_raises_on_all_zero_values()
    print("DONE  34 test_render_radialbar_raises_on_all_zero_values", file=stderr)
    print("START 35 test_render_radialbar_raises_on_mismatched_category_length", file=stderr)
    test_render_radialbar_raises_on_mismatched_category_length()
    print("DONE  35 test_render_radialbar_raises_on_mismatched_category_length", file=stderr)
    print("START 36 test_render_radialbar_raises_on_no_data", file=stderr)
    test_render_radialbar_raises_on_no_data()
    print("DONE  36 test_render_radialbar_raises_on_no_data", file=stderr)
    print("START 37 test_render_radialbar_svg_matches_confirmed_ring_paths", file=stderr)
    test_render_radialbar_svg_matches_confirmed_ring_paths()
    print("DONE  37 test_render_radialbar_svg_matches_confirmed_ring_paths", file=stderr)
    print("START 38 test_render_radar_matches_hand_derived_polygon_fill", file=stderr)
    test_render_radar_matches_hand_derived_polygon_fill()
    print("DONE  38 test_render_radar_matches_hand_derived_polygon_fill", file=stderr)
    print("START 39 test_render_radar_overlapping_series_composite_instead_of_occluding", file=stderr)
    test_render_radar_overlapping_series_composite_instead_of_occluding()
    print("DONE  39 test_render_radar_overlapping_series_composite_instead_of_occluding", file=stderr)
    print("START 40 test_render_radar_raises_on_mismatched_indicator_length", file=stderr)
    test_render_radar_raises_on_mismatched_indicator_length()
    print("DONE  40 test_render_radar_raises_on_mismatched_indicator_length", file=stderr)
    print("START 41 test_render_radar_raises_on_mismatched_series_length", file=stderr)
    test_render_radar_raises_on_mismatched_series_length()
    print("DONE  41 test_render_radar_raises_on_mismatched_series_length", file=stderr)
    print("START 42 test_render_radar_raises_on_wrong_length_series_values", file=stderr)
    test_render_radar_raises_on_wrong_length_series_values()
    print("DONE  42 test_render_radar_raises_on_wrong_length_series_values", file=stderr)
    print("START 43 test_render_radar_raises_on_no_indicators", file=stderr)
    test_render_radar_raises_on_no_indicators()
    print("DONE  43 test_render_radar_raises_on_no_indicators", file=stderr)
    print("START 44 test_render_gauge_matches_hand_derived_needle_and_pivot", file=stderr)
    test_render_gauge_matches_hand_derived_needle_and_pivot()
    print("DONE  44 test_render_gauge_matches_hand_derived_needle_and_pivot", file=stderr)
    print("START 45 test_render_gauge_matches_hand_derived_band_colors", file=stderr)
    test_render_gauge_matches_hand_derived_band_colors()
    print("DONE  45 test_render_gauge_matches_hand_derived_band_colors", file=stderr)
    print("START 46 test_render_gauge_leaves_a_gap_at_the_bottom", file=stderr)
    test_render_gauge_leaves_a_gap_at_the_bottom()
    print("DONE  46 test_render_gauge_leaves_a_gap_at_the_bottom", file=stderr)
    print("START 47 test_render_gauge_clamps_values_beyond_the_range", file=stderr)
    test_render_gauge_clamps_values_beyond_the_range()
    print("DONE  47 test_render_gauge_clamps_values_beyond_the_range", file=stderr)
    print("START 48 test_render_gauge_raises_when_min_value_is_not_less_than_max_value", file=stderr)
    test_render_gauge_raises_when_min_value_is_not_less_than_max_value()
    print("DONE  48 test_render_gauge_raises_when_min_value_is_not_less_than_max_value", file=stderr)
    print("START 49 test_render_gauge_custom_breakpoints_matches_hand_derived_band_colors", file=stderr)
    test_render_gauge_custom_breakpoints_matches_hand_derived_band_colors()
    print("DONE  49 test_render_gauge_custom_breakpoints_matches_hand_derived_band_colors", file=stderr)
    print("START 50 test_render_gauge_custom_breakpoints_default_empty_matches_original", file=stderr)
    test_render_gauge_custom_breakpoints_default_empty_matches_original()
    print("DONE  50 test_render_gauge_custom_breakpoints_default_empty_matches_original", file=stderr)
    print("START 51 test_render_gauge_raises_on_mismatched_breakpoints_and_band_colors_length", file=stderr)
    test_render_gauge_raises_on_mismatched_breakpoints_and_band_colors_length()
    print("DONE  51 test_render_gauge_raises_on_mismatched_breakpoints_and_band_colors_length", file=stderr)
    print("START 52 test_render_gauge_raises_on_non_ascending_breakpoints", file=stderr)
    test_render_gauge_raises_on_non_ascending_breakpoints()
    print("DONE  52 test_render_gauge_raises_on_non_ascending_breakpoints", file=stderr)
    print("START 53 test_render_gauge_raises_on_out_of_range_breakpoint", file=stderr)
    test_render_gauge_raises_on_out_of_range_breakpoint()
    print("DONE  53 test_render_gauge_raises_on_out_of_range_breakpoint", file=stderr)
    print("START 54 test_render_parallel_matches_hand_derived_polylines", file=stderr)
    test_render_parallel_matches_hand_derived_polylines()
    print("DONE  54 test_render_parallel_matches_hand_derived_polylines", file=stderr)
    print("START 55 test_render_parallel_raises_on_mismatched_row_length", file=stderr)
    test_render_parallel_raises_on_mismatched_row_length()
    print("DONE  55 test_render_parallel_raises_on_mismatched_row_length", file=stderr)
    print("START 56 test_render_parallel_raises_on_wrong_length_row", file=stderr)
    test_render_parallel_raises_on_wrong_length_row()
    print("DONE  56 test_render_parallel_raises_on_wrong_length_row", file=stderr)
    print("START 57 test_render_parallel_raises_on_no_dims", file=stderr)
    test_render_parallel_raises_on_no_dims()
    print("DONE  57 test_render_parallel_raises_on_no_dims", file=stderr)
    print("START 58 test_render_single_axis_matches_hand_derived_points", file=stderr)
    test_render_single_axis_matches_hand_derived_points()
    print("DONE  58 test_render_single_axis_matches_hand_derived_points", file=stderr)
    print("START 59 test_render_single_axis_svg_matches_confirmed_circles", file=stderr)
    test_render_single_axis_svg_matches_confirmed_circles()
    print("DONE  59 test_render_single_axis_svg_matches_confirmed_circles", file=stderr)
    print("START 60 test_render_single_axis_color_encoding_reuses_point_channels", file=stderr)
    test_render_single_axis_color_encoding_reuses_point_channels()
    print("DONE  60 test_render_single_axis_color_encoding_reuses_point_channels", file=stderr)
    print("START 61 test_render_single_axis_raises_on_mismatched_channel_length", file=stderr)
    test_render_single_axis_raises_on_mismatched_channel_length()
    print("DONE  61 test_render_single_axis_raises_on_mismatched_channel_length", file=stderr)
    print("START 62 test_render_single_axis_raises_on_no_data", file=stderr)
    test_render_single_axis_raises_on_no_data()
    print("DONE  62 test_render_single_axis_raises_on_no_data", file=stderr)
    print("START 63 test_single_axis_tooltips_report_the_value_alone", file=stderr)
    test_single_axis_tooltips_report_the_value_alone()
    print("DONE  63 test_single_axis_tooltips_report_the_value_alone", file=stderr)
    print("START 64 test_a_wedge_is_titled_by_its_category_and_value", file=stderr)
    test_a_wedge_is_titled_by_its_category_and_value()
    print("DONE  64 test_a_wedge_is_titled_by_its_category_and_value", file=stderr)
    print("START 65 test_a_gauge_is_titled_by_its_one_value", file=stderr)
    test_a_gauge_is_titled_by_its_one_value()
    print("DONE  65 test_a_gauge_is_titled_by_its_one_value", file=stderr)
    print("START 66 test_a_gauge_s_tooltip_group_holds_only_the_needle", file=stderr)
    test_a_gauge_s_tooltip_group_holds_only_the_needle()
    print("DONE  66 test_a_gauge_s_tooltip_group_holds_only_the_needle", file=stderr)
    print("START 67 test_a_radar_ring_is_titled_by_its_series", file=stderr)
    test_a_radar_ring_is_titled_by_its_series()
    print("DONE  67 test_a_radar_ring_is_titled_by_its_series", file=stderr)
    print("START 68 test_radial_tooltips_follow_the_theme_flag", file=stderr)
    test_radial_tooltips_follow_the_theme_flag()
    print("DONE  68 test_radial_tooltips_follow_the_theme_flag", file=stderr)
    print("START 69 test_the_radial_value_marks_draw_their_values_on_request", file=stderr)
    test_the_radial_value_marks_draw_their_values_on_request()
    print("DONE  69 test_the_radial_value_marks_draw_their_values_on_request", file=stderr)
    print("START 70 test_a_wedge_label_sits_outside_its_wedge", file=stderr)
    test_a_wedge_label_sits_outside_its_wedge()
    print("DONE  70 test_a_wedge_label_sits_outside_its_wedge", file=stderr)
    print("ALL DONE", file=stderr)
