"""Combine test modules into batch drivers, so the library compiles once
per driver instead of once per module.

Each `tests/test_*.mojo` module is its own program today, and each
program compiles the library code it imports again -- most of a test
run's wall time, well past running the tests themselves. A driver
imports several modules' `test_*` functions by name and runs each
module's tests as its own `TestSuite`, so the shared library is
compiled once per driver.

A module joins a driver when its `main()` is exactly the standard
`TestSuite.discover_tests[__functions_in_module()]().run()`; one
written by hand instead (there are none today) is left alone and run
as its own program, the way a Parquet-style module with side effects
in `main()` would be. Modules are dealt to drivers by source size,
largest first onto the driver with the least so far, which spreads the
biggest modules out and keeps drivers close to even. Each driver runs
every module even after one fails, prints `== tests/test_x.mojo` before
each so logs read as before, and fails at the end if any module did.

Prints the path of every file `pixi run test` should run: the drivers
under `.test_batches/`, then any module left alone, one per line, so
the caller can capture it directly as a file list.

`_TEST_GROUPS` controls how many driver files a full run builds.
"""

from std.os import listdir, makedirs, path

from _example_docstrings import _read_file, _write_file

comptime _TESTS_DIR = "tests"
comptime _OUT_DIR = ".test_batches"
comptime _TEST_GROUPS = 8
comptime _STANDARD_MAIN = (
    "def main() raises:\n   "
    " TestSuite.discover_tests[__functions_in_module()]().run()"
)


struct _Module(Copyable, Movable):
    """One joinable test module: its path, source size (for
    bin-packing), and the top-level `test_*` functions it defines."""

    var path: String
    var size: Int
    var tests: List[String]

    def __init__(out self, path: String, size: Int, var tests: List[String]):
        self.path = path
        self.size = size
        self.tests = tests^


def _module_name(path: String) -> String:
    """`tests/test_x.mojo` -> `test_x`."""
    var start = _TESTS_DIR.byte_length() + 1
    var end = path.byte_length() - 5
    var base = String(path[byte=start:end])
    return base


def _top_level_tests(source: String) -> List[String]:
    """Every `def test_x() raises:` at column zero, in file order."""
    var tests = List[String]()
    for line in source.split("\n"):
        if not line.startswith("def test_"):
            continue
        if not String(line.strip()).endswith("() raises:"):
            continue
        var paren = line.find("(")
        tests.append(String(line[byte=4:paren]))
    return tests^


def _by_size_desc(a: _Module, b: _Module) -> Bool:
    return a.size > b.size


def _by_path(a: _Module, b: _Module) -> Bool:
    return a.path < b.path


def _pack(var modules: List[_Module], groups: Int) -> List[List[_Module]]:
    """Deal `modules` into at most `groups` buckets, largest first onto
    the bucket with the smallest running total, so compile time per
    bucket stays close to even."""
    sort(modules, _by_size_desc)
    var n = max(1, min(groups, len(modules)))
    var buckets = List[List[_Module]]()
    var sizes = List[Int]()
    for _ in range(n):
        buckets.append(List[_Module]())
        sizes.append(0)
    for idx in range(len(modules)):
        var smallest = 0
        for i in range(1, n):
            if sizes[i] < sizes[smallest]:
                smallest = i
        buckets[smallest].append(modules[idx].copy())
        sizes[smallest] += modules[idx].size
    for i in range(n):
        sort(buckets[i], _by_path)
    return buckets^


def _emit(bucket: List[_Module], n: Int) raises -> String:
    """Write one driver file for `bucket` and return its path."""
    var lines = List[String]()
    lines.append(
        '"""Generated by scripts/build_test_batches.mojo -- do not edit."""'
    )
    lines.append("")
    lines.append("from std.testing import TestSuite")
    for m in bucket:
        var module = _module_name(m.path)
        for test in m.tests:
            lines.append(
                "from "
                + module
                + " import "
                + test
                + " as "
                + module
                + "__"
                + test
            )
    lines.append("")
    lines.append("")
    lines.append("def main() raises:")
    lines.append("    var failed = List[String]()")
    for m in bucket:
        var module = _module_name(m.path)
        lines.append("")
        lines.append('    print("== ' + m.path + '")')
        lines.append("    var " + module + " = TestSuite()")
        for test in m.tests:
            lines.append(
                "    " + module + ".test[" + module + "__" + test + "]()"
            )
        lines.append("    try:")
        lines.append("        " + module + "^.run()")
        lines.append("    except e:")
        lines.append("        print(e)")
        lines.append('        failed.append("' + m.path + '")')
    lines.append("")
    lines.append("    for name in failed:")
    lines.append('        print("FAILED:", name)')
    lines.append("    if len(failed) > 0:")
    lines.append(
        '        raise Error(String(len(failed)) + " module(s) failed")'
    )
    lines.append("")

    var out_path = _OUT_DIR + "/driver_" + String(n) + ".mojo"
    _write_file(out_path, String("\n").join(lines))
    return out_path


def main() raises:
    makedirs(_OUT_DIR, exist_ok=True)

    var entries = listdir(_TESTS_DIR)
    sort(entries)

    var joinable = List[_Module]()
    var alone = List[String]()
    for e in entries:
        if not (e.startswith("test_") and e.endswith(".mojo")):
            continue
        var full = _TESTS_DIR + "/" + e
        if path.isdir(full):
            continue
        var source = _read_file(full)
        if source.find(_STANDARD_MAIN) == -1:
            alone.append(full)
            continue
        var tests = _top_level_tests(source)
        joinable.append(_Module(full, source.byte_length(), tests^))

    var buckets = _pack(joinable^, _TEST_GROUPS)
    var drivers = List[String]()
    for n in range(len(buckets)):
        if len(buckets[n]) == 0:
            continue
        drivers.append(_emit(buckets[n], n))

    for d in drivers:
        print(d)
    for a in alone:
        print(a)
